# These are supported funding model platforms

# github: [ColDog5044] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: # Replace with a single Patreon username
custom: ["https://www.venmo.com/u/ColDog5044", "https://www.paypal.me/collinlaney50"]
